baseURL: https://vasileiospapoutsoglou.netlify.app/
languageCode: en-us
title: Portfolio Website for Vasileios Papoutsoglou
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: Welcome to my Portfolio Website! Feel free to look around.
    title: Hi, my name is Vasileios 
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park
        title: Address - LBS
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: vasileiosp.mfa2022@london.edu
        title: Email
    enable: yes
#    phone:
#      - phone: (000) 000-0000 x1234
#        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: LBS
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/papouts99
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/papoutsoglouu/?hl=en
      - icon: fa-github
        label: GitHub
        url: https://github.com/papoutsoglouv
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/papoutsoglou/
  image: ''
  name: Vasileios 
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: picVP.jpg
        subtitle: A short autobiography
        title: About me
        url: blogs/autobiography
      - image: picFS.jpg
        subtitle: My professional life in an A4 page
        title: CV
        url: blogs/CV
      - image: barca.jpg
        subtitle: My proudest group creation in R
        title: Coding work
        url: blogs/barca
      - image: Gilead.jpg
        subtitle: Nisl Sed Aliquam
        title: Ipsum
        url: blogs/ipsum
#     - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
#  two:
#    buttonText: Get Started
#    enable: yes
#    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
#      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
#      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
#      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
#      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
#      amet pharetra et feugiat tempus."
#   title: Massa libero
#    url: blogs
